FROM evilbeaver/mono-ru:6.8

LABEL MAINTAINER="EvilBeaver <ovsiankin.aa@gmail.com>"

ARG VERSION=night-build

RUN curl http://oscript.io/downloads/$VERSION/deb > oscript.deb \
    && dpkg -i oscript.deb \
    && rm -f oscript.deb
