FROM evilbeaver/mono-ru:6.8

LABEL MAINTAINER="EvilBeaver <ovsiankin.aa@gmail.com>"

ARG VERSION=night-build

RUN curl https://oscript.io/downloads/$VERSION/deb?bitness=x64 > oscript.deb \
    && dpkg -i oscript.deb \
    && rm -f oscript.deb
